name: CI

on: [push, pull_request]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
        ruby: [2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, jruby-9.1, jruby-9.2, truffleruby-20]
        experimental: [false]
        exclude:
          # truffleruby isn't available on windows
          - os: windows-2019
            ruby: truffleruby-20
        include:
          - os: ubuntu-20.04
            ruby: head
            experimental: true
          - os: windows-2019
            ruby: head
            experimental: true
          - os: ubuntu-20.04
            ruby: jruby-head
            experimental: true
          - os: windows-2019
            ruby: jruby-head
            experimental: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
        env:
          SIMULATE_FAILURE: ${{ matrix.experimental }}
