name: CI

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.ruby }} on ${{ matrix.os }}${{ matrix.name_suffix }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
        ruby: ['1.8.7', '1.9.3', '2.0', '2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7', '3.0', jruby-1.7, jruby-9.0, jruby-9.1, jruby-9.2, truffleruby-20]
        architecture: [default]
        name_suffix: ['']
        experimental: [false]
        exclude:
          - os: macos-10.15
            ruby: '1.8.7'
          - os: windows-2019
            ruby: '1.8.7'
          - os: windows-2019
            ruby: jruby-1.7
          - os: windows-2019
            ruby: truffleruby-20
        include:
          - os: windows-2019
            ruby: '2.0'
            achitecture: x86
            name_suffix: ' (x86)'
            experimental: false
          - os: ubuntu-20.04
            ruby: head
            achitecture: default
            name_suffix: ' (experimental)'
            experimental: true
          - os: ubuntu-20.04
            ruby: jruby-head
            achitecture: default
            name_suffix: ' (experimental)'
            experimental: true
          - os: macos-10.15
            ruby: head
            achitecture: default
            name_suffix: ' (experimental)'
            experimental: true
          - os: macos-10.15
            ruby: jruby-head
            achitecture: default
            name_suffix: ' (experimental)'
            experimental: true
          - os: windows-2019
            ruby: head
            achitecture: default
            name_suffix: ' (experimental)'
            experimental: true
          - os: windows-2019
            ruby: jruby-head
            achitecture: default
            name_suffix: ' (experimental)'
            experimental: true
      fail-fast: false
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v2
      - if: startsWith(matrix.ruby, '1.') || startsWith(matrix.ruby, '2.0') || startsWith(matrix.ruby, 'jruby-1.7') || startsWith(matrix.ruby, 'jruby-9.0')
        uses: philr/setup-ruby@legacy-v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: ${{ matrix.architecture }}
          bundler-cache: true
      - if: ${{ !(startsWith(matrix.ruby, '1.') || startsWith(matrix.ruby, '2.0') || startsWith(matrix.ruby, 'jruby-1.7') || startsWith(matrix.ruby, 'jruby-9.0')) }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: ruby --version
      - run: gem --version
      - run: bundle --version
      - run: bundle exec rake test
        env:
          SIMULATE_FAILURE: ${{ matrix.experimental }}
